# Site settings
title: Joel Berman's Blog
subtitle: With all the warts
email: blog@joelberman.net
description: My attempt at a personal journal
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Joel Berman
street_address: 
city: Oxnard
state: CA
zip_code: 93035
country: United States of America
phone: 

# Social settings
500px_url:
facebook_url:
github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
